# Show only on edge because we do not have a tag version
spring:
  info:
    git:
      location: "classpath:git.properties"

app:
  geometry:
    reducerPrecision: 4.0

elasticsearch:
  acronyms:
    name: portal-acronyms-edge

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans,logfile"

logging:
  level:
    au.org.aodn.ardcvocabs: DEBUG
    # for debugging auto-co-indexing purpose
    au.org.aodn.cloudoptimized.service.DataAccessServiceImpl: DEBUG
